minor fixes

diff --git a/autovpn b/autovpn
--- a/autovpn
+++ b/autovpn
@@ -36,9 +36,20 @@ function usage {
 
 bail ()
 {
-	echo -e "${red}code $1"
+	echo -e "${red}Error code $1"
   usage
 	exit 
+}
+
+
+failed ()
+{
+  if [ $1 == "1" ]; then 
+  echo -e "${red}Key already exists in AWS\n"
+  elif [ $1 == "2" ]; then 
+  echo -e "${red}\nFailed to terminate instance"
+  fi
+  exit 
 }
 
 if ( ! getopts "CGSTk:hr:i:z:" opt); then
@@ -137,7 +148,7 @@ fi
 local_path="$(pwd)/${region}_aws_vpn.ovpn"
 
 
-if [ -n "$Cflag" ] && [ -n "$rflag" ] && [ -n "$kflag"  ]; then
+if [ -n "$Cflag" ] && [ -n "$rflag" ] && [ -n "$kflag"  ] ; then
   echo "Creating ec2 instance in $region. This can take some time..."
   instance_ip=$(python create_ec2.py "$keyname" "$instance_type" "$region" "$ami")
   [[ $instance_ip =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]] || bail 4
@@ -156,35 +167,38 @@ if [ -n "$Cflag" ] && [ -n "$rflag" ] && [ -n "$kflag"  ]; then
   echo -e "${green}OpenVPN config file is located at $(pwd)"
 fi 
 
-if [ -n "$Gflag" ] && [ -n "$rflag" ]; then
+if [ -n "$Gflag" ] && [ -n "$rflag" ] ; then
   keypath=$(pwd)
   if [ ! -f "$keypath/${region}_vpnkey.pem" ]; then
     echo -e  "${white}Generating new key pair for $region."
     generate_key=$(python keygen.py "${region}_vpnkey" "$region" "$keypath")
+    [[ $generate_key == "Success" ]] || failed 1
     echo -e "${green}${region}_vpnkey has been created"
     ssh-add -l &>/dev/null
     if [ "$?" == 2 ]; then
-      eval $(ssh-agent) &>/dev/null
+      eval $(ssh-agent -s) &>/dev/null
     fi
-    ssh-add "$keypath/${region}_vpnkey.pem"  &>/dev/null
+    ssh-add "$keypath/${region}_vpnkey.pem" &>/dev/null
   elif [ -f "$keypath/${region}_vpnkey.pem" ]; then
     echo -e "${yellow}A Keypair for this region already exists."
   fi
   echo -e "${green}Use ${region}_vpnkey as keyname to create endpoint."
 fi 
 
-if [ -n "$Sflag" ] && [ -n "$rflag" ]; then
+if [ -n "$Sflag" ] && [ -n "$rflag" ]  ; then
   get_status=$(python get_status.py "$region")
   echo -e "${green}Instances running in ${region}\n ${get_status}"
 fi  
 
-if [ -n "$Tflag" ] && [ -n "$rflag" ] && [ -n "$zflag" ]; then
+if [ -n "$Tflag" ] && [ -n "$rflag" ] && [ -n "$zflag" ]  ; then
    echo -e "${yellow}WARNING: instance ${term_ids} in ${region} will be terminated. This is not reversible"
    read -p "Are you sure you want to continue? y/n :" -n 1 -r
    if [[ $REPLY =~ ^[Yy]$ ]]; then
-    python terminate.py "$region" "$term_ids"
+    termec2=$(python terminate.py "$region" "$term_ids")
+    [[ $termec2 == "Success" ]] || failed 2
     echo -e "\n${green}${term_ids} have been terminated."
    elif [[ $REPLY =~ ^[Nn]$ ]]; then
     echo -e "\n${green}No instances were terminated."
   fi
 fi
+tput sgr0 
